plugins { id("java") }

tasks.withType<JavaCompile>().configureEach {
    // -processing,-serial: warnings in picocli annotation processing and code generated by it
    options.compilerArgs.add("-Xlint:all,-processing,-serial")
    options.compilerArgs.add("-Werror")
}
